# Generated by Django 3.2.8 on 2021-10-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211020_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='account_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='profile_nickname',
        ),
    ]
