# Generated by Django 3.2.8 on 2021-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
